### ISSUE TITLE
-fno-ms-compatibility causes hard to find bugs with lambda const capture

### ISSUE THREAD

**Issue by psalz** [codeplaysoftware/computecpp-sdk#112]
I just spent a considerable amount of time trying to figure out why this kernel crashes somewhere inside ComputeCpp's `process_functor_arguments`:

```c++
my_queue.submit([&](cl::sycl::handler& cgh) {
  auto out = my_buf.get_access<cl::sycl::access::mode::write>(cgh);
  const int some_const_value = 16;
  auto my_kernel = [=](cl::sycl::item<1> item) {
    int cause_capture = some_const_value;
    out[item] = 0.f;
  };
  std::cout << "sizeof(my_kernel) = " << sizeof(my_kernel) << std::endl;
  cgh.parallel_for<class const_crash>(cl::sycl::range<1>(64), my_kernel);
});
```

As it turns out, this only happens on Windows, and only when using a CMake build (not the Visual Studio project wizard).

The culprit becomes apparent when comparing the `*.sycl` files generated by the device compiler.

CMake on Windows:
```
const size_t kernel_info< const_crash >::arg_size = 3;
const size_t kernel_info< const_crash >::arg_sizes[] = {
  8, // __attribute__((address_space(1))) float *
  16, // class cl::sycl::device_index_array
  16, // class cl::sycl::device_index_array
  0
};
```

Visual Studio wizard:
```
const size_t kernel_info< const_crash >::arg_size = 4;
const size_t kernel_info< const_crash >::arg_sizes[] = {
  4, // const int
  8, // __attribute__((address_space(1))) float *
  16, // class cl::sycl::device_index_array
  16, // class cl::sycl::device_index_array
  0
};
```

It appears that clang propagates the `const` value into the lambda, while MSVC (presumably) does not. This causes a mismatch between the lambda and the kernel at runtime.

When comparing the device compiler flags used by the two projects, I found the `-fno-ms-compatibility` flag set for CMake builds [here](https://github.com/codeplaysoftware/computecpp-sdk/blob/a8808b4adbe28e344f1637d6fb18d88df4d57b04/cmake/Modules/FindComputeCpp.cmake#L69). And, lo and behold, removing this flag fixes the issue.

I'm not sure if the original reasons for including this flag are still relevant, nor the specifics of the issue, but I tried to compile the program above with `const char16_t some_const_value = 16;`, which appeared to work just fine.

Tested with ComputeCpp 0.6.1, 0.7.0 and 0.8.0, on Windows 10 and Ubuntu 16.04.

**Comment by DuncanMcBain** [comment]
Hi @psalz, thanks for your report. We have actually seen this crash before, affecting only MSVC, so it's fantastic that you have further refined the problem. It sounds like this flag is the root of the problem.

It looks like the issue reported way back in 2013 (on the mailing list) continued to be a problem until Clang 6, so I'm not totally sure what to do here. I am tempted to remove it, but if you could confirm that all samples *and* tests pass with the flag removed on MSVC I'd be very grateful (tests can be enabled with -DCOMPUTECPP_SDK_BUILD_TESTS=1). I can't test Visual Studio here at the moment, but if you confirm that it doesn't break the SDK testing then I will likely remove the flag and we can offer a solution to users who run into the undefined types issue.

If you build in Debug (i.e. use the debug CRT) then you'll likely see one or two failures in the virtual pointer tests. I know about them, but haven't had a chance to investigate the root cause and fix them yet - I'd not worry about them.

@wdx04, I believe you might have been experiencing the same issue in #93 - would you be able to try removing the -fno-ms-compatibility flag too?
