### ISSUE TITLE
Support for debian platform

### ISSUE THREAD

**Issue by ThijsWithaar** [codeplaysoftware/computecpp-sdk#140]
In FindComputeCpp.cmake, there's a line `-isystem ${ComputeCpp_INCLUDE_DIRS}`.
replacing that by `-isystem /usr/include/x86_64-linux-gnu` makes it work on debian(buster).

Without the modification, the sycl compile step cannot find `stdlib.h`.
It'd be nice if this could be handled in a reliable/standard way by FindComputeCpp.cmake

**Comment by DuncanMcBain** [comment]
Hi @ThijsWithaar,
For the most part, we run on Ubuntu systems without any problems, so I'm surprised that you are running into issues. In fact, given that compute++ is based on Clang, the path you're suggesting is one that it should look for normally. What configuration are you running? Where did you install ComputeCpp? I don't tend to put it in system directories, since I need to change my version relatively often.

(I'm asking these questions because ComputeCpp_INCLUDE_DIRS is a variable exactly relating to the location of the ComputeCpp headers, as documented here: https://cmake.org/cmake/help/v3.5/manual/cmake-developer.7.html#standard-variable-names. Indeed if you then set the corresponding ComputeCpp_DIR when configuring CMake, it all should work as expected - it's worked in every configuration we've tested internally.)

**Comment by ThijsWithaar** [comment]
>  What configuration are you running

Debian, buster/unstable on an x64.

> Where did you install ComputeCpp?

Into /usr. Using `dpkg-deb`, I generated a minimal .deb package to allow removing/updating.
Note that `/usr/include/x86_64-linux-gnu` is relatively empty, it contains stl headers and such,
but user libraries are in `/usr/include`.

>  if you then set the corresponding ComputeCpp_DIR when

I've tried adding the following to `CMakeListst.txt`, didn't help:
```set(ComputeCpp_DIR CACHE PATH "/usr/include/x86_64-linux-gnu")```

It might be something silly on my side, but I've not been able to get it to work without the (hacky) change in `FindComputeCpp.cmake`.

**Comment by DuncanMcBain** [comment]
So `ComputeCpp_DIR` shouldn't be set to the include path, `FindComputeCpp.cmake` uses that path to find all the components of ComputeCpp. In this case, you should be doing `-DComputeCpp_DIR=/usr`, I think.

I know what's going on - there is a problem with installing the headers to `/usr/include`, in that `FindComputeCpp.cmake` will add `/usr/include` as an include directory to the compiler directly, which causes problems for the usual include order (which will normally check `/usr/include` much later, see [this page](https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html) for details). I think in this case we should remove it from the list of include directories, I'll see if I can quickly come up with something to remove it.

**Comment by DuncanMcBain** [comment]
It was actually a really simple change, I should have paid a little more attention to your first comment (many thanks to @mmha for pointing that out!). It's testing on travis, PR number #141, so you can try that branch if you can't wait the couple of minutes for the fix to be merged :stuck_out_tongue:

**Comment by ThijsWithaar** [comment]
It works over here, thanks!

**Comment by DuncanMcBain** [comment]
Fixed in #141
