### ISSUE TITLE
Compile error with gcc/clang in MSYS2

### ISSUE THREAD

**Issue by pasuka** [codeplaysoftware/computecpp-sdk#142]
Dear all,
I've tried to build a ComputeCpp application with [MSYS2](http://www.msys2.org/) under Windows-7

> OS:            Windows-7 64bit
> Compiler:  gcc-8.2.0/clang-6.0.1 in MSYS2

When it began to building ComputeCpp integration header file for **/samples/accessors/accessors.cpp.sycl** gcc/clang thrown an error message:

> error: __float128 is not supported on this target struct __is_floating_point_helper<__float128>

I tried to find a solution by google and failured.
Is that means VS is the only choice under windows OS?

BTW, in China mainland the authentication of Google's reCAPTCHA in login/register process is blocked by [GFW](https://en.wikipedia.org/wiki/Great_Firewall)

Best regards,
Ted

**Comment by rodburns** [comment]
Hi Ted,
The MSYS2/MinGW64 implementations have a different ABI. 
We compile with VS2015 and implement a C++ API so if you try to use this with MSYS2 it will not work because there is no compatibility layer.

With regard to the reCAPTCHA, we unfortunately need to integrate with this and the Google one works well. However, if you can suggest any alternatives that work better in China we can investigate using these instead.
Best Regards,
Rod.
