### ISSUE TITLE
Forced include mechanism in FindComputeCpp.cmake does not work in Visual Studio 2015

### ISSUE THREAD

**Issue by jpg85** [codeplaysoftware/computecpp-sdk#159]
Forced include method doesn't work properly under VS2015.
The line:
set(forceIncludeFlags "/FI ${includedFile} /TP")
Gets split by spaces and the "includedFile" becomes part of the "AdditionalOptions" and a blank "ForcedIncludeFiles" tag is created.

If the line is changed to:
set(forceIncludeFlags "/FI${includedFile} /TP")
The ForcedInclude tag is properly populated with "includedFile". Note that I haven't tested the solution for paths with spaces or multiple files.

**Comment by MathiasMagnus** [comment]
Yes, apologies for that. The workaround code path for this issue was [recently removed](https://github.com/codeplaysoftware/computecpp-sdk/pull/149/commits/52b9b7b4059195614315f9d11d8dafa724c342bb) as a simplification to handling Visual Studio generators. It was I who introduced this workaround a long while ago and forgot what setup required it. Because VS 2017 does not need it anymore, I went ahead and removed it.

Seems like I'll have to put it back with a version check, and it should trigger only when using VS 2015.
