### ISSUE TITLE
Terminated after throwing instance of cl::sycl::invalid_object_error

### ISSUE THREAD

**Issue by AD2605** [codeplaysoftware/computecpp-sdk#239]
Hello, I am new to SYCL development and have just started exploring the field. 
I am following the code vector addition from HelloSYCL https://developer.codeplay.com/products/computecpp/ce/guides/sycl-guide/hello-sycl
On compilation and running I get the following output - 

`Running on GeForce RTX 2070`
`terminate called after throwing an instance of 'cl::sycl::invalid_object_error'`
with exit code 134 (interrupted by signal 6: SIGABRT)
What could be going wrong? 
TIA

**Comment by rodburns** [comment]
You need to compile using the "ptx" flag to execute on Nvidia hardware. Are you doing that?
There are instructions for the flag in [this guide](https://developer.codeplay.com/products/computecpp/ce/guides/platform-support/targeting-nvidia-ptx).
Let me know if that helps.

**Comment by mcleary** [comment]
If you're building the SDK with CMake you can use the CMake option `-DCOMPUTECPP_BITCODE=ptx64` and cmake will take care of passing the correct flags to the compiler

**Comment by AD2605** [comment]
I missed passing that option, Thanks for your help.. 
However I did run Cmake using with that option followed by make - 
the output is as follows - 
`Running on GeForce RTX 2070
terminate called after throwing an instance of 'cl::sycl::invalid_object_error'
Aborted (core dumped)
`

**Comment by mcleary** [comment]
Could you try a clean build? Sometimes the binary code is not updated when you change this flag

**Comment by AD2605** [comment]
I still get the same error

**Comment by rodburns** [comment]
Can you copy in here the cmake command you are using please?
Also if you open the .sycl file that was generated during compilation you will see if it is using the correct instructions.
For example it should show something like this, the key bit being the `nvptx64`:

`unsigned char SYCL_hello_world_nvptx64[] {`

**Comment by AD2605** [comment]
There is no .sycl file generated. 
I am running `cmake -DCOMPUTECPP_BITCODE= ptx64 CMakeLists.txt
` followed by `make`
my Cmake looks like - 


`cmake_minimum_required(VERSION 3.16)
project(ComputeCPP)

set(CMAKE_CXX_STANDARD 14)

add_executable(ComputeCPP main.cpp)
target_include_directories(ComputeCPP PUBLIC "/usr/local/computecpp/include/")
target_link_libraries(ComputeCPP "/usr/local/computecpp/lib/libComputeCpp.so")

target_include_directories(ComputeCPP PUBLIC "/usr/local/cuda/include/")
target_link_libraries(ComputeCPP  "/usr/local/cuda/lib64/libOpenCL.so")`

**Comment by mcleary** [comment]
So, I thought you were building `computecpp-sdk` but apparently you are building your own project. The CMake flag that I mention will only work if you use the provided `FindComputeCpp.cmake` file. Your CMake file will not work out-of-the-box since you need to understand a little bit more how to compile for the device you're targetting.

The best and easiest solution of for you to copy the `FindComputeCpp.cmake` module provided in the SDK. Look into the repository, particularly the `samples` folder for more information on how to write the CMake file to properly invoke the device compiler.

If you are having more trouble with this I'll suggest for you to take a deeper look into ComputeCpp's documentation

**Comment by AD2605** [comment]
Thanks a lot @mcleary, I will do as suggested

**Comment by AD2605** [comment]
Sorry for bothering, this might be a silly question.
 Just to clarify, I downloaded the computeCpp 2.0.0 community edition, extracted it and placed it in the folders mentioned above in cmake. I thought this would run out of the box as we already have a .so file. Is there anything else we need to do after downloading computecpp ?

**Comment by mcleary** [comment]
Here are some step-by-step instructions
```
git clone https://github.com/codeplaysoftware/computecpp-sdk.git
cd computecpp-sdk
mkdir build
cd build
cmake .. -DComputeCpp_DIR=<where you extracted ComputeCpp>
make -j8
./samples/simple-vector-add
```

**Comment by DuncanMcBain** [comment]
Because the code has to run on accelerator hardware and host compilers cannot output code that runs on them natively, we ship our own compiler (`compute++`) that can output code that runs on them (in this case, PTX that can run on Nvidia GPUs). `FindComputeCpp.cmake` exposes a function which sets that up for you (and is how I'd recommend starting out), the integration guide on the website explains what is happening and how to integrate it with existing code. You can also use `compute++` as the host compiler if you prefer.

**Comment by AD2605** [comment]
Oh okay now I get it.. 
Thanks a lot
