### ISSUE TITLE
Running SYCL program in MSVC Debug mode throws std::bad_array_new_length 

### ISSUE THREAD

**Issue by martinstarkov** [codeplaysoftware/computecpp-sdk#256]
Cloned the latest computecpp-sdk samples and built project files using the included CMake. 
Running on Visual Studio v16.9.4 2019 on Windows 10 in Debug mode. 
Exception points to the queue construction (with both default constructor and with specific ones):
![image](https://user-images.githubusercontent.com/5933654/119833256-a04cdc00-bf07-11eb-9dd9-0cb682b408ce.png)
This seems like a ComputeCpp bug and nothing to do with the samples as I have tested in my own code and it occurs with any simple queue construction. Perhaps not though, as Visual Studio seems to link with the correct debug library, found in the linker dependencies:
``` \computecpp\lib\ComputeCpp_d.lib ```

**Comment by razorbeard** [comment]
I'm joinning this thread because I have the same issue. I am using Visual Studio 16.11.2 on Windows 10. Here's computecpp_info output on my machine : 
![computecpp_info](https://user-images.githubusercontent.com/88341236/133074991-5b0d4975-bf5f-436f-b2c8-01e392940436.png)

Build has been done through CMake with the following command line from the guide, plus an extra command for my device : 
`cmake .. -G "Visual Studio 16 2019" -A x64 -DComputeCpp_DIR="C:\Program Files\Codeplay\ComputeCpp" -DCOMPUTECPP_BITCODE=ptx64`. No problem so far.

Building `simple_vector_add` in release mode seems to work, but in debug mode the same error as @martinstarkov is thrown :
![debug_mode_computecpp](https://user-images.githubusercontent.com/88341236/133075770-b5831276-97ff-416f-b7ba-e33e6c9fc72b.png)

**Comment by DuncanMcBain** [comment]
The CMake should pick up the debug version of the ComputeCpp library when building in debug mode, but it's possible that it's not. Can you check the CMake cache (it's in the build folder) for the entry `COMPUTECPP_RUNTIME_LIBRARY_DEBUG`?

**Comment by razorbeard** [comment]
Hello Duncan, here's the following lines from my CMakeCache file : 
![cmakecache_output](https://user-images.githubusercontent.com/88341236/133287483-67cf7bd5-8e3f-4c4e-8575-02ad3b8f883d.png)

It seems to be ok in Debug mode. In the project properties in C/C++ > Code Generation > Runtime Library, if I manually switch the /MDd flag to /MT only it works. I have also tested previous versions of CMake in case of deprecating functions, but I still get the same problem.

**Comment by DuncanMcBain** [comment]
Yes those are the right libraries. Are you saying that if you change from the *debug* CRT to the *release* CRT, debug builds start working again? If that's the case, that's definitely unexpected (I don't know what those flags do, I'm afraid, but I'm guessing from some documentation).

**Comment by razorbeard** [comment]
Yes, here's the flag I have changed in the simple-add-vector sample :
![runtime_mdd](https://user-images.githubusercontent.com/88341236/133309185-f91c420e-7474-49be-80e5-3212a5190527.png)

Changing it to this one make it works :
![runtime_mt](https://user-images.githubusercontent.com/88341236/133309259-da897be6-75e2-4b1b-b3b7-6ee60a723cd1.png)

Could it be a bug in the ComputeCpp_d.lib file ?

**Comment by Bensuo** [comment]
> I have also tested previous versions of CMake in case of deprecating functions, but I still get the same problem.

Did you try any version of CMake `3.14` or lower? I believe `3.15` introduced the change that causes this issue.

**Comment by razorbeard** [comment]
Doesn't seems to work either. I tried versions `3.14` and `3.15` but the same error is raised.
Below `3.14` there's not support for Visual Studio 2019 unfortunately.
