### ISSUE TITLE
can't download computecpp 

### ISSUE THREAD

**Issue by littlefish-img** [codeplaysoftware/computecpp-sdk#264]
can anybody send me the computecpp ,because the  website of codeplay.com now can't be registert,so I can't dowanload the file.Emai-address: 943516934@qq.com. Thanks!

**Comment by rodburns** [comment]
Hi, ComputeCpp requires registration for your to download it. Usually this issue is caused by the "captcha" we use which can be blocked by some browser settings, or it could also be because it is blocked in your region (for example if you are in China) since the captcha is a Google service. Have you tried a different browser?
