### ISSUE TITLE
Need a method to detect compute++ compiler

### ISSUE THREAD

**Issue by wdx04** [codeplaysoftware/computecpp-sdk#72]
Hi,
I want to check if my source code is being processed by the compute++ compiler.
Is there a compiler definition like __clang__ or _MSC_VER for the compute++ compiler?

**Comment by DuncanMcBain** [comment]
Hi,
There is! __SYCL_DEVICE_ONLY__ is defined when the device compiler is compiling the code, and not otherwise. You should be careful though, there can be some real problems if you use conditional compilation where the device compiler is concerned (for example, if you capture a variable but only inside the scope of __SYCL_DEVICE_ONLY__, you're going to get at least weird behaviour but probably just crashes). If you can tell me, what's your use case?

**Comment by wdx04** [comment]
I'm using computecpp 0.5.0 with Visual Studio 2015+CMake 3.10 and I also use the https://github.com/sakra/cotire module for precompiled header management. Unfortunately cotire will remove the /FI(force include) option added by add_sycl_to_target function(the reason is unclear for now). So I try to include the generated .sycl header in another way:

```C++
#include "stdafx.h"
#ifndef __clang__
#include "mysource.cpp.sycl"
#endif
```

If the source code is being compiled by the compute++ compiler, then do not include the .sycl file, and if the source code is being compiled by the Visual C++ compiler, then include it.

Above code works for me, but it would be better to use a SYCL or ComputeCpp specific definition. SYCL_DEVICE_ONLY seems to have no effect for this use case.

**Comment by DuncanMcBain** [comment]
There aren't any ComputeCpp specific ones. This didn't work because I'm a victim of highlighting!
```c++
#ifndef __SYCL_DEVICE_ONLY__
#include "thefile.sycl"
#endif
```
I've never used cotire, kind of annoying that it removes the force include. Something that might be interesting to you is the include-after property as documented in the CMake files and in the "using function objects" sample code. It changes the actual target of the compilation to the sycl file, it might work but I'm guessing it might also just totally fail as a force include is still used to make everything work properly.

**Comment by wdx04** [comment]
Added the underscores and it works as expected. Thank you.
