### ISSUE TITLE
-std=gnu++11 gets attached automatically

### ISSUE THREAD

**Issue by domantasjurkus** [codeplaysoftware/computecpp-sdk#94]
This is not exactly a computecpp-sdk issue, but I am unable to change the `-std` compiler flag as it gets overwritten by a default set (as I understand) by computecpp. My Makefile:
```
cmake_minimum_required(VERSION 3.2.2)
project(Tutorial)
set(CMAKE_CXX_STANDARD 11)

set(CMAKE_CXX_COMPILER "/home/dom/computecpp-ce-0.6.0/bin/compute++")

set(COMPUTECPP_PACKAGE_ROOT_DIR /home/dom/computecpp-ce-0.6.0)

add_executable(main ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)

target_compile_options(main PRIVATE "-std=gnu++14")
```
Make verbose:
```
/home/dom/computecpp-ce-0.6.0/bin/compute++     -std=gnu++14 -std=gnu++11 -o CMakeFiles/main.dir/main.cpp.o -c /home/dom/playground/sycl/main.cpp
```
The `-std=gnu++14` gets overwritten by `-std=gnu++11` and I cannot figure out where it's coming from. Any advice?

**Comment by DuncanMcBain** [comment]
We stopped setting CXX_STANDARD a little while ago, or should have - but as far as I can tell the third line of your script is the one setting this variable: https://cmake.org/cmake/help/v3.2/prop_tgt/CXX_STANDARD.html. I can't remember why, but CMake seems to prefer the gnu++ variant of the flag instead of c++.

I guess you're trying to use compute++ as a host compiler, too - this is supported by the compiler but hasn't yet been integrated properly into our CMake. The flag `-sycl-driver` will automatically compile for device and host inside one invocation, if you're not using it already. Drop some more messages here if you manage to get it working - or otherwise ;)

**Comment by michel-steuwer** [comment]
Just a guess, but maybe `set(CMAKE_CXX_STANDARD 14)` would help ...

**Comment by domantasjurkus** [comment]
Bingo, answers was right in from of me, thanks!
